import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js meets Parade!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://bop-component.netlify.app/bop-component.js" type="module"></script>      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> + <a href="https://tryparade.com/">Parade</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <h2>First, add the following line just before &lt;/Head&gt;  </h2>
        <code className={styles.code}>&lt;script src="https://bop-component.netlify.app/bop-component.js" type="module"&gt;&lt;/script&gt;   </code>

        <h2>Second, add the following line just before the final  &lt;/div&gt;  </h2>
        <code className={styles.code}>&lt;bop-component storeId='ckr13tx1g0001hloptworzsxd' left='true' &gt;&lt;/bop-component&gt;   </code>
      
        <h2>DONE!</h2>


        <h3 className={styles.card}>
          <a href="https://github.com/morganpage/nextjs-parade">SOURCE CODE FOR THIS PAGE IS HERE</a>
        </h3>
      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      
      <bop-component storeId='ckr13tx1g0001hloptworzsxd' left='true' ></bop-component>
    </div>
  )
}
